function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)

end

function update(self, dt)

end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)
	if action_id == hash("mouse_button_left") and action.released then
		local world_pos = camera.screen_xy_to_world(action.screen_x, action.screen_y)
		local id = factory.create("#factory", world_pos)
		print(id)
	end
end

function on_reload(self)

end